### ISSUE TITLE
Use #selector

### ISSUE THREAD

**Issue by catalandres** [s4cha/Stevia#17]
Xcode 7.3 beta 5 spits out the following when compiling Stevia:
```
./Carthage/Checkouts/Stevia/Stevia/Stevia/Stevia/Source/Stevia+Tap.swift:37:33: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
```

**Comment by s4cha** [comment]
Thanks for the report man, I guess it's because string selectors will be deprecated in the next version of swift/Xcode, so we'll need to update that. Did that prevent you from using Stevia?

**Comment by catalandres** [comment]
Not at all. It's just a warning under Swift 2.2.

I haven't checked if implementing the suggested change would hurt for those
running &lt;2.2.

If it doesn't, it's a really easy fix.

> On Mar 15 2016, at 3:56 am, S4cha &lt;notifications@github.com&gt; wrote:  

>

> Thanks for the report man, I guess it's because string selectors will be
deprecated in the next version of swift/Xcode, so we'll need to update that.
Did that prevent you from using Stevia?

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or view it on GitHub:  
<https://github.com/s4cha/Stevia/issues/17#issuecomment-196707052>![](https://
github.com/notifications/beacon/ABkpjZEExiQvE2oxlCsJkuWARSnnCsI2ks5ptmYMgaJpZM
4Huaq8.gif)

**Comment by s4cha** [comment]
Closing this for now, when swift 2.2 is officially out, we''ll add the following fix : 
```swift
#if swift(>=2.2)
    addTarget(self, action: #selector(tapped), forControlEvents: .TouchUpInside)
#else
    addTarget(self, action: "tapped", forControlEvents: .TouchUpInside)
#endif
```

**Comment by catalandres** [comment]
Then, instead storing the code in an issue, how about creating a branch for the feature and merging it when Xcode 7.3 gets released?

**Comment by s4cha** [comment]
@catalandres this has been added in the latest release -> https://github.com/s4cha/Stevia/blob/master/Stevia/Stevia/Stevia/Source/Stevia+Tap.swift
Thanks again for the catch :)
