### ISSUE TITLE
what about the contentView of tableViewCell

### ISSUE THREAD

**Issue by peiweichen** [s4cha/Stevia#19]
subview would be added to cell's view or contentView?

**Comment by s4cha** [comment]
For `UITableViewCell` and `UICollectionViewCell`, subviews would be added to the contentView, as recommended :)
-->
https://github.com/s4cha/Stevia/blob/master/Stevia/Stevia/Stevia/Source/Stevia+Hierarchy.swift

**Comment by krzat** [comment]
Actually, how would you use this with dequeueReusableCell?

**Comment by s4cha** [comment]
Well it shouldn't change anything, do you have a precise example in mind ?

As an example, here is how you would write a UITableViewCell with Stevia :

```swift
class FriendCell:UITableViewCell {
    
    let avatar = UIImageView()
    let name = UILabel()
    
    required init?(coder aDecoder: NSCoder) { super.init(coder: aDecoder)}
    override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        
        sv(
            avatar,
            name.style(nameStyle)
        )
        
        avatar.size(50).centerVertically()
        alignHorizontally(|-20-avatar-name-20-|)
    }
    
    func nameStyle(l:UILabel) {
        l.font = .systemFontOfSize(24)
        l.textColor = .blueColor()
    }
}
```


```swift

// In viewDidLoad, register your cell for dequeue
tableView.registerClass(FriendCell.self, forCellReuseIdentifier: "FriendCell")

// Later, in cellForRowAtIndexPath
let cell = tableView.dequeueReusableCellWithIdentifier("FriendCell", forIndexPath: indexPath) as! FriendCell
```
The whole dequeue process is the same with or without Stevia, since this is just pure UIKit :)
Hope it helps ;)

**Comment by krzat** [comment]
Ooops, sorry. didn't know about registerClass method. :D Thanks for info.
