### ISSUE TITLE
Combine Stevia with Material Design

### ISSUE THREAD

**Issue by arimunandar** [s4cha/Stevia#21]
Hi, 

I try to combine Stevia with [Material Design](https://github.com/CosmicMind/Material), i just edit Stevia example end join with Material, but i can't modify style UITextField to TextField Material, how to config Material and Stevia?

**Comment by s4cha** [comment]
Hi @arimunandar, the style syntax is made to work with native UIKit controls.

If you want to support the style syntax for other components, you need to implement the bridge yourself at the moment.
Here is how it would look like in your case :
```swift
public extension TextField {
    public override func style(styleClosure:(f:TextField) -> Void) -> TextField {
        styleClosure(f:self)
        return self
    }
}
```
Let me know how this works for you ;)

**Comment by krzat** [comment]
I figured out how to make style generic in MR #22, but I'm not sure why it wasn't implemented like this before, maybe I missed something.

**Comment by s4cha** [comment]
We have to to test it but as far as I tested it it's great, simple and solves the problem of having to bridge every single UI element!! great job :clap:

**Comment by s4cha** [comment]
@arimunandar Can you confirm this solves your issue?

**Comment by arimunandar** [comment]
Where i use this code ?

`public extension TextField {
    public override func style(styleClosure:(f:TextField) -> Void) -> TextField {
        styleClosure(f:self)
        return self
    }
}`

on UIView ?

**Comment by s4cha** [comment]
Hi @arimunandar it should actually work without adding any code now thanks to @krzat update (2.1.0) yesterday. You should be able to call .style on your `TextField` instance :)
Just make sure you update Stevia (`carthage update Stevia` or `pod update`)

**Comment by arimunandar** [comment]
Hi @s4cha i have update stevia, and i got some error, please check a picture :
[Errors](http://snag.gy/u4qRu.jpg)

Thanks :)

**Comment by s4cha** [comment]
Try replacing `UITextfield` by `TexField` :)

**Comment by arimunandar** [comment]
Hi @s4cha  If i replacing with this code : 

`func passwordFieldStyle(f:TextField) {`
i got error on this :  [Error](http://snag.gy/bDKPc.jpg)

Thanks :)

**Comment by s4cha** [comment]
Hey @arimunandar , here is a playground that where I tried to reproduce your issue, but it works well on my end
```swift
import UIKit

// Stevia code
public extension UIAppearance {
    public func style(styleClosure:(Self)-> Void) -> Self {
        styleClosure(self)
        return self
    }
}

// Mocking Material texfield
class TextField:UITextField {
    var customProperty = ""
}

// Your style function
func tfStyle(tf:TextField) {
    tf.customProperty = "Changed !"
}


let textField = TextField()
textField.style(tfStyle) //  apply style, compiles well in Playground
textField.customProperty // ->  "Changed !"
```

**Comment by arimunandar** [comment]
Thanks @s4cha :)

**Comment by s4cha** [comment]
Did you fix your issue?

**Comment by arimunandar** [comment]
Not Yet @s4cha T_T
can you write step to fix my issue please? :)

**Comment by arimunandar** [comment]
Hi @s4cha , can you fix my issue?
Thanks :)

**Comment by s4cha** [comment]
Hey @arimunandar, I'm afraid I can't do much without more code.
Is the project you're working on open source or would there be a way for you to share me the code?
Thanks ;)

**Comment by arimunandar** [comment]
Hi @s4cha this my code, i just change LoginViewStevia TextField with Material [TextField](https://github.com/CosmicMind/Material/wiki/TextField) but i get error like this : 

![screen shot 2016-03-22 at 10 07 52 am](https://cloud.githubusercontent.com/assets/12929878/13941058/352335fc-f016-11e5-8f5f-810a86fa5e5c.png)


```swift
import UIKit
import SteviaLayout
import Material

class LoginMaterialStevia:UIView {
    
    let email = UITextField()
    let password = TextField()
    let login = UIButton()
    
    convenience init() {
        self.init(frame:CGRectZero)
        // This is only needed for live reload as injectionForXcode
        // doesn't swizzle init methods.
        render()
    }
    
    func render() {
        backgroundColor = .grayColor()
        
        sv([
            email.placeholder("Email").style(fieldStyle), //.style(emailFieldStyle),
            password.placeholder("Password").style(fieldStyle).style(passwordFieldStyle),
            login.text("Login").style(buttonSytle).tap(loginTapped)
            ])
        
        layout([
            100,
            |-email-| ~ 80,
            8,
            |-password-| ~ 80,
            "",
            |login| ~ 80,
            0
            ])
    }
    
    func fieldStyle(f:UITextField) {
        f.borderStyle = .RoundedRect
        f.font = UIFont(name: "HelveticaNeue-Light", size: 26)
        f.returnKeyType = .Next
    }
    
    func passwordFieldStyle(f:TextField) {
        f.secureTextEntry = true
        f.returnKeyType = .Done
        
        f.placeholder = "First Name"
        f.placeholderTextColor = MaterialColor.grey.base
        f.font = RobotoFont.regularWithSize(20)
        f.textColor = MaterialColor.black
        
        f.titleLabel = UILabel()
        f.titleLabel!.font = RobotoFont.mediumWithSize(12)
        f.titleLabelColor = MaterialColor.grey.base
        f.titleLabelActiveColor = MaterialColor.blue.accent3
        
        let image: UIImage? = MaterialIcon.close
        
        let clearButton: FlatButton = FlatButton()
        clearButton.pulseColor = MaterialColor.grey.base
        clearButton.pulseScale = false
        clearButton.tintColor = MaterialColor.grey.base
        clearButton.setImage(image, forState: .Normal)
        clearButton.setImage(image, forState: .Highlighted)
        
        f.clearButton = clearButton

    }
    
    
    func buttonSytle(b:UIButton) {
        b.backgroundColor = .lightGrayColor()
    }
    
    func loginTapped() {
        //Do something
    }
}
```

how to fix that? Thanks :)

**Comment by s4cha** [comment]
Hey @arimunandar, 

The issue happens because the `placeholder` call returns a bare UITextfield instance.

You could force cast into `TextField` :
```swift
(password.placeholder("Password") as! TextField).style(fieldStyle).style(passwordFieldStyle),
```
Or applying the placeholder at the end would make it work 
```swift
password.style(fieldStyle).style(passwordFieldStyle).placeholder("Password"),
```

We haven't thought of this use case (UIKit control subclasses) and we will take this into account for the upcoming updates !

Thanks a lot for your time and patience :)

**Comment by s4cha** [comment]
Hey @arimunandar as of 2.1.2 content helpers such as `placeholder("")` should return the right subclass :)
