### ISSUE TITLE
Get UIViews from controller

### ISSUE THREAD

**Issue by frgmt** [s4cha/Stevia#24]
Hey thank you s4cha for your library. I like the way it layouts everything.
I tried to use the pattern you're using for creating views.

But I'm wondering how I get the views from outside the Controller. When I want to make some operations which are triggered in override functions like viewWillDissapear I can't call them from inside the controller which implements the view inside the "override loadView()" function. 

**ViewController-Class**
```swift
class MapViewController: UIViewController {

    let locationManager = CLLocationManager()
    
    override func loadView() {
        view = MapView()
    }

    override func viewDidLoad() {
        super.viewDidLoad()

        // self.clusteringManager.delegate = self
        
        // self.viewModel = MapViewModel(mapView: self.view, clusteringManager: self.clusteringManager)
        // self.viewModel.getAllAnnotations()
        
        // Initial setup of map
        // initialSetup()
    }
    
    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
    }

    override func viewWillDisappear(animated: Bool) {
        super.viewWillDisappear(animated)
    }
    
    private func initialSetup() {
        
        // Init Location Manager
        // initLocationManager()
        
        // Init Layout
        // initLayout()
        
        // Set camera to user location
        if let userLocation: CLLocationCoordinate2D = locationManager.location?.coordinate {
            self.mapView.setCenterCoordinate(userLocation, zoomLevel: 10.0, animated: true)
        }
    }
}
```

**View-Class**
```swift
class MapView: UIView {
    let mapView = MKMapView()
    
    convenience init() {
        self.init(frame: CGRectZero)
        
        backgroundColor = .redColor()

        sv(
            // Do stuff
        )
    }

}
```

Now I need the mapView of the View-Class. But I have no idea how to get it from the ViewController.

**Comment by s4cha** [comment]
Hey @frgmt, glad you ask :)

Here is how we typically do it :

```swift
class LoginVC: UIViewController {

    let v = LoginView() 
    override func loadView() { view = v }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        v.loginButton.tap(login)
    }

    func login() {
      // do something
    }
}
```
Essentially referencing the view outside the `loadView` method.

As always with programming there are many ways to get the same result, another strategy would be to cast `view` into `myview` through` a custom getter :)

Hope it helps ;)

**Comment by s4cha** [comment]
@frgmt Can we close the issue? (we'll add a step in the REDAME clarifying accessing view properties form the controller)

**Comment by frgmt** [comment]
Yes! Actually it was really obvious. So thanks for pointing this out again.

**Comment by iraycd** [comment]
I guess this should be included in the example. It's crucial. 👍

**Comment by s4cha** [comment]
@iraycd Just added it to the README :)

**Comment by iraycd** [comment]
It's not a good pattern to have everything in just one page.
It's try to make a **Github Page**.
