### ISSUE TITLE
pod installation

### ISSUE THREAD

**Issue by rostik** [s4cha/Stevia#25]
im having problems installing with pod. it installs and adds your files to my project, but then it doesn't recognize sv() and layout() inside my classes. could you help? thanks

**Comment by s4cha** [comment]
Hey @rostik 
Can you confirm your `Podfile.lock` has   `- SteviaLayout (2.1.0)`, which the latest version.
`sv()` and `layout()` were introduced recently and their previous counterparts are `sv([])` and `layout([])`

I know it sounds stupid but did you add `import SteviaLayout` at the top of the file?

**Comment by rostik** [comment]
adding 2.1.0 to pod file, fixed it, thank you!

On Mon, Mar 21, 2016 at 5:05 PM, S4cha <notifications@github.com> wrote:

> Hey @rostik <https://github.com/rostik>
> Can you confirm your Podfile.lock has - SteviaLayout (2.1.0), which the
> latest version.
> sv() and layout() were introduced recently and their previous
> counterparts are sv([]) and layout([])
>
> I know it sounds stupid but did you add import SteviaLayout at the top of
> the file?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/s4cha/Stevia/issues/25#issuecomment-199485604>
>



-- 
Thanks,
- Rostik
