### ISSUE TITLE
Chainable heightEqualsWidth

### ISSUE THREAD

**Issue by edubarr** [s4cha/Stevia#26]
Is there any reason why `heightEqualsWidth` is not chainable? It would certainly make is simpler to have a layout like the one I'm currently working on:
`|-10-label-20-imageButton.heightEqualsWidth()-10-|`

At the moment I just add that constraint after the `layout(...)` call. It would be very simple to have `heightEqualsWidth` return a reference to the view and the above approach would just work.

By the way, thanks for the great library! It has streamlined my code quite a bit. :100:

**Comment by s4cha** [comment]
Hey @edubarr nice catch! This is indeed something that we should be able to chain, like all the others :)
I'll add it tonight and update you, thanks for the eagle eye :+1:

**Comment by s4cha** [comment]
@edubarr this is now supported as of 2.1.1 https://github.com/s4cha/Stevia/commit/ba9540d68f9b5c6fc7089d8bb586e62ea24e73b7
