### ISSUE TITLE
Expression was to complex to be solved in reasonable time

### ISSUE THREAD

**Issue by Neku** [s4cha/Stevia#29]
Hello,
when I enter this layout: 
```       
  layout([50,  
            prontoLogo.centerHorizontally(),  
            50,  
            |-20-whyMailLabel-20-|,  
            |-20-emailTextfield-20-|,  
            10,  
            |-50-confirmButton-50-|])
```
Xcode fails to compile with the following message:
"Expression was to complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expression"

Any clue?

**Comment by s4cha** [comment]
Hello @Neku 

_"Expression was to complex to be solved in reasonable time"_ can happen in Stevia, since Xcode has a hard time finding the right `-` operator overload. However it usually only happens with very long horizontal layouts with multiple margins.

I could reproduce your issue and got rid of the compiler warning by removing the array syntax []
```swift
layout(
    50,
    prontoLogo.centerHorizontally(),
    50,
    |-20-whyMailLabel-20-|,
    |-20-emailTextfield-20-|,
    10,
    |-50-confirmButton-50-|
)
```

Could you confirm it fixes it on your end as well ?

**Comment by waterlee23** [comment]
Have the same problem:
`
    layout(
        18,
        |-15-avatarImageView-15-userNameLabel-""-likeButton-20-|,
        0
    )
`

**Comment by Neku** [comment]
Thank you, I didn't try flattening the array, but I ended up calling layout twice (which is not really nice)

**Comment by s4cha** [comment]
@waterlee23 @Neku 

Here a three valid solutions for avoiding this annoying compiler error. All of them aim at making it easier for the compiler to find the right `-` operator version.


```swift
// Solution 1
// Putting margins in separate variables
let m:CGFloat = 15
let m2:CGFloat = 20
|-m-avatarImageView-m-userNameLabel-""-likeButton-m2-|

// Solution 2
// Breaking it into smaller layouts
|-15-avatarImageView-15-userNameLabel
likeButton-20-|

// Solution 3
// Using a double dash `--` version so that the compiler doesn't have to go through
// all the existing `-` operator overloads defined by UIKit/Foundation
|-15--avatarImageView--15--userNameLabel--""--likeButton--20-|
```


Here is the double dash version that we use internally, this only forwards calls.
As a side note, this is our preferred way internally and are planning to release this on master soon :)
```swift
infix operator -- {associativity left}

public func -- (left: UIView, right: CGFloat) -> PartialConstraint {
    return left-right
}

public func -- (left: SideConstraint, right: UIView) -> UIView {
    return left-right
}

public func -- (left: [UIView], right: SideConstraint) -> [UIView] {
    return left-right
}

public func -- (left:UIView, right: SideConstraint) -> UIView {
    return left-right
}

public func -- (left: PartialConstraint, right: UIView) -> [UIView] {
    return left-right
}

public func -- (left: UIView, right: UIView) -> [UIView] {
    return left-right
}

public func -- (left: [UIView], right: CGFloat) -> PartialConstraint {
    return left-right
}

public func -- (left: [UIView], right: UIView) -> [UIView] {
    return left-right
}

public func -- (left: UIView, right: String) -> Space {
    return left-right
}

public func -- (left: [UIView], right: String) -> Space {
    return left-right
}

public func -- (left: Space, right: UIView) -> [UIView] {
    return left-right
}

public func -- (left: UIView, right: SteviaFlexibleMargin) -> PartialFlexibleConstraint {
    return left-right
}

public func -- (left: [UIView], right: SteviaFlexibleMargin) -> PartialFlexibleConstraint {
    return left-right
}

public func -- (left: PartialFlexibleConstraint, right:UIView) -> [UIView] {
    return left-right
}
```
PS: Please excuse the late reply :)

**Comment by bartoszhernas** [comment]
@s4cha Even better solution in my opinion is to provide the type to numbers. It is basically the same solution as 1) but better readable.

      view.layout(
            CGFloat(0),
            |-CGFloat(8)-titleLabel-CGFloat(4)-priceLabel-CGFloat(8)-| ~ CGFloat(36),
            CGFloat(0)
        )
        return view

**Comment by s4cha** [comment]
@bartoszhernas Thanks, your solution has been documented in the README as well ;)
