### ISSUE TITLE
I'm not sure if i doing it right

### ISSUE THREAD

**Issue by Swissmaik** [s4cha/Stevia#33]
I have started with this fantastic library, but have one little problem:
I have a TableViewCell in which i like to have on the left side a date and on the right side a city.
It works on the first two rows, but after that on the third and fourth it will not display correctly.

<img width="1055" alt="bildschirmfoto 2016-04-22 um 15 09 38" src="https://cloud.githubusercontent.com/assets/5399697/14742551/25e0141c-089d-11e6-993f-32a36054474d.png">

It seems that i make some mistake but did not find a solution :(

**Comment by s4cha** [comment]
Hey @Swissmaik,

This does look like a bug indeed, your layout seems fine to me.
I would just suggest you try having a flexible space between the city and the date. I think the cell reuse might break the layout if the margin is fixed, but it's just a guess.
Have you tried something like this ?
```swift
layout(
  0,
  |-10-city,
  \\other views...
  0
)
alignHorizontally(city-(>=20)-time-10-|)
```

Could you send over your Cell code for me to check if this is a bug we'll get it fixed for the next release :)
Hope it helps,

PS: I see that you styled your elements with a StyeHelper, which makes them compoasable 👍

**Comment by Swissmaik** [comment]
Hi @s4cha 

I have maked the flexible space between the city and the date.
It seems that this works now.

Here is the requested cell code, i'm do not programming long, so it could be a little bit "overcoded" :)

 class UebungTableViewCell: UITableViewCell {
    
    let beschreibungLabel = UILabel()
    let datumLabel = UILabel()
    let ortLabel = UILabel()
    let rememberanceImage = UIImageView()
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        
        sv(
            beschreibungLabel.text("Beschreibung Label"),
            datumLabel.text("Datum Label").style(StyleHelper.smallStyleUILabel),
            ortLabel.text("Ort Label").style(StyleHelper.smallStyleUILabel),
            rememberanceImage.size(20)
        )
        
        layout(
            5,
            |-datumLabel-(>=1)-ortLabel-|,
            2,
            |-beschreibungLabel-(>=1)-rememberanceImage-|,
            5
        )
    }
    
    func setUebung(pfObject: PFObject?) {
        
        let dateFormatter = NSDateFormatter()
        dateFormatter.locale = NSLocale(localeIdentifier: "de_CH")
        dateFormatter.timeZone = NSTimeZone(abbreviation: "GMT")

        if let pfObject = pfObject {
            beschreibungLabel.text = pfObject["uebungsTitel"] as? String ?? "unbekannt"
            ortLabel.text = pfObject["uebungsOrt"] as? String ?? "unbekannt"

            dateFormatter.dateFormat = "dd. MMMM yyyy 'um' HH:mm"
            datumLabel.text = dateFormatter.stringFromDate((pfObject["uebungsDatum"] as? NSDate)!)
        }
    }
 }

thanks a lot.
