### ISSUE TITLE
flexible height constraint

### ISSUE THREAD

**Issue by navisingh** [s4cha/Stevia#34]
How does one set a flexible height constraint:

Instead of a fixed height as in:
|-myView-| ~20
I tried |-myView-| ~(>=20)
did not work.

**Comment by s4cha** [comment]
Hi @navisingh,
This is not (yet) supported but it's definitely on our short term roadmap :p 

In the mean time, you can use the standard way :

```swift
let c = NSLayoutConstraint(item: v, attribute: .Height, relatedBy: .GreaterThanOrEqual, toItem: nil, attribute: .NotAnAttribute, multiplier: 1, constant: 20)
addConstraint(c)
```

Hope it helps ;)

**Comment by s4cha** [comment]
@navisingh 
Latest version `2.1.3` now packs overloads for flexible margins, so you'll be now able to use 
```swift
|-myView-| ~ (>=20)
```
Cheers,

**Comment by navisingh** [comment]
thanks
