### ISSUE TITLE
Priorities.

### ISSUE THREAD

**Issue by navisingh** [s4cha/Stevia#35]
How does one set priorities on constraints?

**Comment by s4cha** [comment]
Priorities are not supported at the moment.
In order to set them, you need to use the good'ol standard api :)

```swift
let c = NSLayoutConstraint(item: v, attribute: .Top, relatedBy: .Equal, toItem: v, attribute: .Top, multiplier: 1, constant: 0)
c.priority = 751
addConstraint(c)

```
Just realised default code constraints priority is 1000 (required) which can be problematic because it makes them non overridable. Maybe we need to set default priority lower in the future to account for this use case.

**Comment by s4cha** [comment]
Hello @navisingh,  Thanks for your input on this.
Form now on Stevia constraints are created with a priority of 751 and in order to change the priority, the native api will be used.

**Comment by ChanchalW** [comment]
It's not changing the priority for constraints. When I debug it  
po view2.heightConstraint?.priority
▿ Optional<Float>
  - Some 1000.0

height  = constraint(item: view3, attribute: .height, relatedBy: .equal, toItem: nil, attribute: .height, multiplier: 1, constant: 129)
        width = constraint(item: view3, attribute: .width, relatedBy: .equal, toItem: nil, attribute: .width, multiplier: 1, constant: 145)
height.priority = 999
width.priority = 999   
view.addConstraints([height,width])

What's incorrect here?

**Comment by s4cha** [comment]
Hi @ChanchalW,
The print says view2 and the rest says view3 :)
This just caught my eye.
It might just be a typo though, I’ll have more time to look into it tomorrow. 
Cheers

**Comment by ChanchalW** [comment]
Yes thats just typing error and I am getting all priorities as 1000 not 751

**Comment by s4cha** [comment]
Hi @ChanchalW,

This is quite puzzling..
This

```swift 
        let view3 = UIView()
        
        sv(
            view3
        )
        
        view3.backgroundColor = .red
        view3.centerInContainer()
        view3.width(32)
        
        let height = constraint(item: view3,
                                attribute: .height,
                                relatedBy: .equal,
                                toItem: nil,
                                attribute: .height,
                                multiplier: 1,
                                constant: 129)
        let width = constraint(item: view3,
                               attribute: .width,
                               relatedBy: .equal,
                               toItem: nil,
                               attribute: .width,
                               multiplier: 1,
                               constant: 145)
        
        print(height.priority)
        print(width.priority)
        addConstraints([height,width])
```

yields on my end :

```swift
751.0
751.0
```

Could you give me more code?

Maybe your version of Stevia is not up to date?

PS:   The width, height + addConstraints calls can be simplified using :
```swift
        view3.height(129).width(145)
```

**Comment by ChanchalW** [comment]
Hi @s4cha, I solved it. Problem was that my views were added in storyboard and then I was setting its constraints. Adding view by coding solved the problem.
