### ISSUE TITLE
View in background

### ISSUE THREAD

**Issue by pikanezi** [s4cha/Stevia#36]
Hello,
Thank you for your work, this library made me want to code my views (instead of using IB).

I have a question though, how would you create a layout where you would have an image which fill the whole background and still render views on front of it.

I really like the feeling that every views in the screen are in one unique place (layout()) but I'm afraid that it's not possible in this case.

Thank you,

Vincent

**Comment by s4cha** [comment]
Hi @pikanezi,
Thank **you** for choosing code over XML :p 
`layout()` is the preferred way of laying things out vertically but it's totally fine having thing outside of a layout block :)
In your case you need `image.fillContainer()`, which is the equivalent of :
```swift
layout(
  0,
  |image|,
  0
)
```

Hope it helps ;)

**Comment by pikanezi** [comment]
Thank you @s4cha,

What if I want to add something on top of this image?

Thank you for your help and time, I really appreciate it :)

Vincent

**Comment by s4cha** [comment]
@pikanezi 

```swift
sv(
    backgroundImage,
    label,
    separator
)

backgroundImage.fillContainer()
layout(
    label,
    13,
    |separator| ~ 2,
    0
)
```

**Comment by pikanezi** [comment]
Oh I see! Thank you for your help :)
