### ISSUE TITLE
"|-10-label-(>=8)-|" not supported

### ISSUE THREAD

**Issue by cp3hnu** [s4cha/Stevia#37]
"|-10-label-(>=8)-|" not supported
and 
```
layout(
    10,
    label1,
    >=8
    label2,
    10
)
```
not supported

**Comment by s4cha** [comment]
Hi @cp3hnu thanks a lot for noticing that.
These are on our radar indeed :) 
I'll ping you once it's live !

**Comment by s4cha** [comment]
@cp3hnu , @Nevermole, @hieuvo

I am happy to announce that both cases are now supported in the latest version (2.2.0) 🎉

Cheers,
