### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by telip007** [s4cha/Stevia#39]
How can I layout two buttons, one aligned to left, the other to the right, I tried '|-button1-button2-|' but it doesn't work...

**Comment by richardmcclellan** [comment]
Try this:
```
|-button1
button2-|
```

Or, if you're using the layout method, you can do it like this:
```
layout(
[|-button1, button2-|]
)
```

**Comment by richardmcclellan** [comment]
Try this:

```
|-button1
button2-|
```

Or, if you're using the layout method:

```
layout(
[|-button1, button2-|]
)
```

**Comment by s4cha** [comment]
Hi @telip007 

```swift
|-button1-button2-|
```
is the equivalent of 
```swift
|-8-button1-8-button2-8-|
```
"-" being the standard margin (8)
I guess what you want is 
```swift
|-b1-""-b2-|]
or
|-b1-(>=8)-b2-|
```

Hope it helps ;)

**Comment by s4cha** [comment]
@richardmcclellan 

Writing your 2nd suggestion would stack the buttons vertically, as `layout` is used for vertical layouts ;)

```swift
layout(
  |-button1,
  button2-|
)
```

**Comment by s4cha** [comment]
@telip007 did that solve your issue ?

**Comment by telip007** [comment]
Yes, sorry forgot answer, thank you by the way :)
Am 31.05.2016 23:39 schrieb S4cha <notifications@github.com>:@telip007 did that solve your issue ?
