### ISSUE TITLE
InjectionForXcode

### ISSUE THREAD

**Issue by seyhunak** [s4cha/Stevia#4]
I can't work with InjectionForXcode, can you provide an example viewController implementation @s4cha 

Thanks.

**Comment by s4cha** [comment]
Hey @seyhunak  here is the view controller code to support injection :

```swift
class ViewController: UIViewController {

    override func loadView() { view = LoginViewStevia() }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Here we want to reload the view after injection
        on("INJECTION_BUNDLE_NOTIFICATION") {
            self.view = LoginViewStevia()
        }
    }
}
```

 As far as the View is concerned, here is how we would modify  the LoginViewStevia from the example project to support injection :
[LoginViewStevia.swift](https://github.com/s4cha/Stevia/blob/master/Stevia/LoginExample/LoginNadir/LoginViewStevia.swift)

```swift
class LoginViewStevia:UIView {
    
    let email = UITextField()
    let password = UITextField()
    let login = UIButton()
    
    convenience init() {
        self.init(frame:CGRectZero)
        render()
    }
    
    func render() {
        backgroundColor = .whiteColor()

        sv([
            email.placeholder("Email").style(fieldStyle), //.style(emailFieldStyle),
            password.placeholder("Password").style(fieldStyle).style(passwordFieldStyle),
            login.text("Login").style(buttonSytle).tap(loginTapped)
        ])
        
        layout([
            100,
            |-email-| ~ 80,
            8,
            |-password-| ~ 80,
            "",
            |login| ~ 80,
            0
        ])
    }

    func fieldStyle(f:UITextField) {
        f.borderStyle = .RoundedRect
        f.font = UIFont(name: "HelveticaNeue-Light", size: 26)
        f.returnKeyType = .Next
    }
    
    func passwordFieldStyle(f:UITextField) {
        f.secureTextEntry = true
        f.returnKeyType = .Done
    }
    
    func buttonSytle(b:UIButton) {
        b.backgroundColor = .lightGrayColor()
    }
    
    func loginTapped() {
        //Do something
    }
}
```
Essentially you just want to make sure you call "render()" in your init because injectionForXCode doesn't swizzle init method.

Let me know how it goes :)

**Comment by seyhunak** [comment]
I did replaced with your implementation.
I works as expected. But I need to run "Inject Source" command from Product > Inject Source from Xcode overtime I made a change, how can i made it change while editing?

Thanks

**Comment by Mathieu-o** [comment]
Well it can't work live, but you can just hit "ctrl-x" which is the shortcode for "Inject Source" whenever you want to inject.

**Comment by kioshimafx** [comment]
Hey guys! I make demo project with this code and Stevia + InjectionForXcode [https://github.com/FXSolutions/FXDemoXCodeInjectionPlugin)](repo link) ;)
