### ISSUE TITLE
Constraint can be animated?

### ISSUE THREAD

**Issue by boardmain** [s4cha/Stevia#40]
Hi constraint change can be made with animation?

**Comment by s4cha** [comment]
@boardmain 

Sure :)

The way to animate constraints using autolayout is by calling `layoutIfNeeded()` in an animation block.
Below is an example : 
```swift
image.height(100)

// And later on
image.heightConstraint?.constant = 200

// Animate if we want to
UIView.animateWithDuration(2) {
    self.layoutIfNeeded()
}
```
Hope it helps ;)

**Comment by maximkhatskevich** [comment]
Great! Works like a charm. Thank you @s4cha!
