### ISSUE TITLE
I would like to make two or three text fields occupy the same amount of space horizontally:

### ISSUE THREAD

**Issue by RafaelGadret** [s4cha/Stevia#43]
Hello!
I would like to make two or three text fields occupy the same amount of space horizontally:
how do I do?
like in
layout(
|-textfield1-textfield2-|
)
or 
layout(
|-textfield1-textfield2-textfield3-|
)

**Comment by s4cha** [comment]
Hi @RafaelGadret 

Calling `layout` is only needed for vertical layouts, in order to have text fields occupy the same amount of space horizontally, we can use the following :
```swift
alignHorizontally(equalWidths(|-textfield1-textfield2-textfield3-|))
```

We can note here that nothing places them on the Y Axis, so  we could add something like : 
```swift
textfield1.top(10)
//or
textfield1.centerVertically()
```

Hope it helps ;)

**Comment by RafaelGadret** [comment]
Thanks a lot!
