### ISSUE TITLE
swift 3.0 release?

### ISSUE THREAD

**Issue by navisingh** [s4cha/Stevia#59]
Any plans to provide a swift 3.0 release soon?

**Comment by KarlHarnois** [comment]
+1 on that issue

**Comment by s4cha** [comment]
Hey guys, I'm out today but it's very probable that this will be available tomorrow night :)

**Comment by KarlHarnois** [comment]
amen!

**Comment by s4cha** [comment]
Hi guys I just worked on latest swift3 migration and it's tricker than expected so it's not production ready yet. Indeed operator overloading changed a bit :  [https://github.com/apple/swift-evolution/blob/master/proposals/0077-operator-precedence.md](url), and as you know, Stevia uses operator overloading heavily.
59/60 tests pass though so you can give a try to the swift 3 branch which compiles :)

**Comment by s4cha** [comment]
Hey guys, happy to announce that the pre release is here -> https://github.com/s4cha/Stevia/releases/tag/3.0.0
Please let me know how it goes :)

**Comment by s4cha** [comment]
@navisingh @KarlHarnois can we close this ?
