### ISSUE TITLE
Center aligning view in container

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [s4cha/Stevia#63]
Hi, thanks for your effort on making this wonderful pod. As part of learning to use this library, I started by taking a simple example of making a view align center to its superview. But unfortunately its not working. I would like to get some assistance to fix the issue.

`class LoginView: UIView {

    let centerView = UIView()
    
    convenience init() {
        self.init(frame:CGRect.zero)
        backgroundColor = AppColors.turboYellow
        
        centerView.backgroundColor = AppColors.mantisGreen
        centerView.height = 150.0
        centerView.width = 310.0
        centerView.centerInContainer()
        sv(
            centerView
        )
    }
}`

![output](https://cloud.githubusercontent.com/assets/7369485/19038141/c91fbe90-8997-11e6-8d9d-861dca329a8d.png)

Instead of `centerView.centerInContainer()`, I tried

`centerView.centerVertically()
        centerView.centerHorizontally()`

and that didn't work either.

**Comment by s4cha** [comment]
Hi @AnnieNinaJoyceV 

Constraints must be set after setting up the view hierarchy :) 
Something like this should work 

```swift 
let centerView = UIView()

convenience init() {
    self.init(frame:CGRect.zero)

    // View Hierarchy
    sv(
        centerView
    )

    // Layout
    centerView.height(150.0).width(310.0).centerInContainer()

    // Style
    backgroundColor = AppColors.turboYellow
    centerView.backgroundColor = AppColors.mantisGreen

}
```

Let me know how this goes :)

**Comment by AnnieNinaJoyceV** [comment]
Thank you so much for the help 👍 
Realized that after digging the example project :)
